#!/usr/bin/env bash
# Regenerate the client's database types from the linked Supabase project.
#
# Run it after every migration. The client can't read either table — the anon
# surface is one RPC — but the types still pin src/api/live.ts to the real column
# names and nullability, so a rename breaks `tsc` instead of production.
#
#   ./scripts/pull-types.sh          from the linked project (production)
#   ./scripts/pull-types.sh --local  from `supabase start`
#
# Use --local while a migration is written and not yet applied to production:
# pulling from the linked project would quietly rewrite the types back to the
# old schema and the client would typecheck against a database it is about to
# stop matching.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=../client/src/api/database.types.ts
SOURCE="${1:---linked}"

{
  echo "// Generated by server/scripts/pull-types.sh — do not hand-edit."
  echo "// Regenerate after every migration:  cd server && ./scripts/pull-types.sh"
  echo "//"
  echo "// get_daily() shows up as \`Returns: Json\` because it returns jsonb. The"
  echo "// concrete shape of that payload lives in src/api/live.ts, which builds it"
  echo "// out of the column types below so a rename can't slip through."
  echo
  supabase gen types typescript "$SOURCE"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
